export const CountryCodeDictionary = new Map([
	['andorra', 'AD'],
	['united arab emirates', 'AE'],
	['afghanistan', 'AF'],
	['antigua and barbuda', 'AG'],
	['anguilla', 'AI'],
	['albania', 'AL'],
	['armenia', 'AM'],
	['angola', 'AO'],
	['antarctica', 'AQ'],
	['argentina', 'AR'],
	['american samoa', 'AS'],
	['austria', 'AT'],
	['australia', 'AU'],
	['aruba', 'AW'],
	['åland islands', 'AX'],
	['azerbaijan', 'AZ'],
	['bosnia and herzegovina', 'BA'],
	['barbados', 'BB'],
	['bangladesh', 'BD'],
	['belgium', 'BE'],
	['burkina faso', 'BF'],
	['bulgaria', 'BG'],
	['bahrain', 'BH'],
	['burundi', 'BI'],
	['benin', 'BJ'],
	['saint barthélemy', 'BL'],
	['bermuda', 'BM'],
	['brunei darussalam', 'BN'],
	['bolivia (plurinational state of)', 'BO'],
	['bonaire, sint eustatius and saba', 'BQ'],
	['brazil', 'BR'],
	['bahamas', 'BS'],
	['bhutan', 'BT'],
	['bouvet island', 'BV'],
	['botswana', 'BW'],
	['belarus', 'BY'],
	['belize', 'BZ'],
	['canada', 'CA'],
	['cocos (keeling) islands', 'CC'],
	['congo, democratic republic of the', 'CD'],
	['central african republic', 'CF'],
	['congo', 'CG'],
	['switzerland', 'CH'],
	["côte d'ivoire", 'CI'],
	['cook islands', 'CK'],
	['chile', 'CL'],
	['cameroon', 'CM'],
	['china', 'CN'],
	['colombia', 'CO'],
	['costa rica', 'CR'],
	['cuba', 'CU'],
	['cabo verde', 'CV'],
	['curaçao', 'CW'],
	['christmas island', 'CX'],
	['cyprus', 'CY'],
	['czechia', 'CZ'],
	['germany', 'DE'],
	['djibouti', 'DJ'],
	['denmark', 'DK'],
	['dominica', 'DM'],
	['dominican republic', 'DO'],
	['algeria', 'DZ'],
	['ecuador', 'EC'],
	['estonia', 'EE'],
	['egypt', 'EG'],
	['western sahara', 'EH'],
	['eritrea', 'ER'],
	['spain', 'ES'],
	['ethiopia', 'ET'],
	['finland', 'FI'],
	['fiji', 'FJ'],
	['falkland islands (malvinas)', 'FK'],
	['micronesia (federated states of)', 'FM'],
	['faroe islands', 'FO'],
	['france', 'FR'],
	['gabon', 'GA'],
	['united kingdom of great britain and northern ireland', 'GB'],
	['grenada', 'GD'],
	['georgia', 'GE'],
	['french guiana', 'GF'],
	['guernsey', 'GG'],
	['ghana', 'GH'],
	['gibraltar', 'GI'],
	['greenland', 'GL'],
	['gambia', 'GM'],
	['guinea', 'GN'],
	['guadeloupe', 'GP'],
	['equatorial guinea', 'GQ'],
	['greece', 'GR'],
	['south georgia and the south sandwich islands', 'GS'],
	['guatemala', 'GT'],
	['guam', 'GU'],
	['guinea-bissau', 'GW'],
	['guyana', 'GY'],
	['hong kong', 'HK'],
	['heard island and mcdonald islands', 'HM'],
	['honduras', 'HN'],
	['croatia', 'HR'],
	['haiti', 'HT'],
	['hungary', 'HU'],
	['indonesia', 'ID'],
	['ireland', 'IE'],
	['israel', 'IL'],
	['isle of man', 'IM'],
	['india', 'IN'],
	['british indian ocean territory', 'IO'],
	['iraq', 'IQ'],
	['iran (islamic republic of)', 'IR'],
	['iceland', 'IS'],
	['italy', 'IT'],
	['jersey', 'JE'],
	['jamaica', 'JM'],
	['jordan', 'JO'],
	['japan', 'JP'],
	['kenya', 'KE'],
	['kyrgyzstan', 'KG'],
	['cambodia', 'KH'],
	['kiribati', 'KI'],
	['comoros', 'KM'],
	['saint kitts and nevis', 'KN'],
	["korea (democratic people's republic of)", 'KP'],
	['korea, republic of', 'KR'],
	['kuwait', 'KW'],
	['cayman islands', 'KY'],
	['kazakhstan', 'KZ'],
	["lao people's democratic republic", 'LA'],
	['lebanon', 'LB'],
	['saint lucia', 'LC'],
	['liechtenstein', 'LI'],
	['sri lanka', 'LK'],
	['liberia', 'LR'],
	['lesotho', 'LS'],
	['lithuania', 'LT'],
	['luxembourg', 'LU'],
	['latvia', 'LV'],
	['libya', 'LY'],
	['morocco', 'MA'],
	['monaco', 'MC'],
	['moldova, republic of', 'MD'],
	['montenegro', 'ME'],
	['saint martin (french part)', 'MF'],
	['madagascar', 'MG'],
	['marshall islands', 'MH'],
	['north macedonia', 'MK'],
	['mali', 'ML'],
	['myanmar', 'MM'],
	['mongolia', 'MN'],
	['macao', 'MO'],
	['northern mariana islands', 'MP'],
	['martinique', 'MQ'],
	['mauritania', 'MR'],
	['montserrat', 'MS'],
	['malta', 'MT'],
	['mauritius', 'MU'],
	['maldives', 'MV'],
	['malawi', 'MW'],
	['mexico', 'MX'],
	['malaysia', 'MY'],
	['mozambique', 'MZ'],
	['namibia', 'NA'],
	['new caledonia', 'NC'],
	['niger', 'NE'],
	['norfolk island', 'NF'],
	['nigeria', 'NG'],
	['nicaragua', 'NI'],
	['netherlands', 'NL']
]);
